### ISSUE TITLE
Unable to install with node 4.0.0 

### ISSUE THREAD

**Issue by shyamchandranmec** [natevw/fermata#56]
Here is my node version: v4.0.0

and here is the npm version: 2.14.2

I am getting the following error

 node-proxy@0.9.0 install /Users/shyam/Documents/projects/newsman/node_modules/fermata/node_modules/node-proxy
> node-gyp configure build

  CXX(target) Release/obj.target/nodeproxy/src/node-proxy.o
In file included from ../src/node-proxy.cc:33:
In file included from ../src/./node-proxy.h:40:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {

**Comment by natevw** [comment]
Hi, thanks for the report! You're probably best off trying the 'upcoming' branch, which I think can be installed via "fermata@0.11.0-alpha3b". That makes node-proxy an optional module, and then when/if V8's builtin proxies become enabled by default you should be able to use those if you wish. Otherwise the browser-friendly "parentheses" syntax is always available.

(I really need to get that branch finished up and pushed as the main version, especially if this binary dependency is now broken again by another node version bump!)

**Comment by shyamchandranmec** [comment]
@natevw
Thanks for the update
